I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "game/screens.rpy", line 270, in set_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\bootstrap.py", line 316, in bootstrap
    renpy.main.main()
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\main.py", line 578, in main
    run(restart)
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\main.py", line 143, in run
    renpy.execution.run_context(True)
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\execution.py", line 908, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "renpy/common/00start.rpy", line 189, in script
    python:
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00start.rpy", line 190, in <module>
    renpy.execute_default_statement(True)
  File "C:\Users\yoina\OneDrive\Documents\RenPy\renpy-7.3.5-sdk\renpy\exports.py", line 3495, in execute_default_statement
    i.set_default(start)
  File "game/screens.rpy", line 270, in set_default
    default quick_menu = True
Exception: store.quick_menu is being given a default a second time.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
AddictionVN 1.0
Fri Dec 25 21:07:14 2020
